Update Mlucas.c to implement nbdy’s PRP bugfix
primesearch/Mlucas pull request #17
Opened 2024-04-04 21:34 UTC by xanthe-cat

Updates version to 21.0.1;
Implements nbdy’s important fix for checking PRP result if a probable prime is found #15;
Some output modifications for Suyama test by Gary Gostin;
Update of GitHub links to further info (primesearch)

2024-04-05 05:55 UTC, ldesnogu approved these changes
This looks good to me.

2024-04-05 12:38 UTC, tdulcet requested changes
Thank you for submitting this PR! Overall it looks good, I just see one issue and I have a minor question.

It seem weird to have a v21.0.1 without first having 21.0, but this is probably the correct thing to do considering all of the changes we have made.

Also, thanks for updating those GitHub links. It looks like I missed them in https://github.com/primesearch/Mlucas/commit/37bf1707f00f633e258bb2bcf7288bf53aada7a5.

2024-04-05 12:38 UTC, tdulcet commented on src/Mlucas.c
> +					if(arrtmp[j] != 0x0) { isprime = 0; break; }
This should be `arrtmp[i]`, otherwise it would only check the index after the last.

Also, can you please add a brief comment here with a link to #15, similar to what you did in #11.

2024-04-05 12:38 UTC, tdulcet commented on src/Mlucas.c
> +//	sprintf(cstr, " this gives an average %20.15f bits per digit\n",1.0*p/n);	strcat(cbuf,cstr);
This is probably a question for Gary, but why is this line commented out?

2024-04-05 21:07 UTC, xanthe-cat commented on src/Mlucas.c
> +//	sprintf(cstr, " this gives an average %20.15f bits per digit\n",1.0*p/n);	strcat(cbuf,cstr);
This is one of my changes, rather than Gary’s. I find it difficult to understand why this line is there, except that perhaps Ernst was wanting to print some other information in the Suyama PRP code and so copied and pasted a line for elsewhere as an example, and then failed to modify it. At the end of line 3297 `strcat(cbuf,cstr);` concatenates a string which has already been printed; and 3298 then does the same, resulting in output that looks like this:
```
F23: using FFT length 512K = 524288 8-byte floats, initial residue shift count = 0
This gives an average   16.000000000000000 bits per digit
The test will be done in form of a 3-PRP test.
Suyama-PRP on cofactors of F23: using FFT length 512K = 524288 8-byte floats.
The test will be done in form of a 3-PRP test.    ← line 3297, cstr had not been cleared
 this gives an average   16.000000000000000 bits per digit    ← line 3298 cstr is redundant (see 4 lines above here!)
Doing one mod-F23 squaring of iteration-8388607 residue [Res64 = 50E1F11B55196BBB] to get Fermat-PRP residue
```

2024-04-05 21:09 UTC, xanthe-cat commented on src/Mlucas.c
> +					if(arrtmp[j] != 0x0) { isprime = 0; break; }
Done and done. (I picked up that error when I tested it and then forgot about it when copying nbdy’s fix to here.)

2024-04-05 21:17 UTC, xanthe-cat commented
It is a little weird to be releasing 21.0.1 but, also, this release is without its principal developer, who perhaps would not have released this at all with substantial parts of the feature set absent.
As it is, the versions here masquerading as ‘20.1.1’ have effectively if unofficially been used as the _de facto_ version ‘21.0’, if not _de jure_.

2024-04-05 22:22 UTC, merged

2024-04-06 13:44 UTC, tdulcet commented on src/Mlucas.c
> +//	sprintf(cstr, " this gives an average %20.15f bits per digit\n",1.0*p/n);	strcat(cbuf,cstr);
OK, thanks for the explanation. I agree that it makes sense to comment out this line.